apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgbranch.fullname" . }}-proxy
  labels:
    {{- include "pgbranch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    {{- include "pgbranch.selectorLabels" . | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.proxy.port }}
      targetPort: proxy
      {{- if .Values.proxy.service.nodePort }}
      nodePort: {{ .Values.proxy.service.nodePort }}
      {{- end }}
