package pgctl

import (
	"bytes"
	"context"
	"errors"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/abd-ulbasit/pgoverlay/internal/runtime"
)

// runFixup executes basebackupFixupScript with sh against dir, with a stub
// postgres binary that reports serverVersion.
func runFixup(t *testing.T, dir, serverVersion string) string {
	t.Helper()
	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skip("no sh")
	}
	stubs := t.TempDir()
	stub := "#!/bin/sh\necho '" + serverVersion + "'\n"
	if err := os.WriteFile(filepath.Join(stubs, "postgres"), []byte(stub), 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(sh, "-c", basebackupFixupScript, "pgoverlay-seed-fixup", dir)
	cmd.Env = append(os.Environ(), "PATH="+stubs+string(os.PathListSeparator)+os.Getenv("PATH"))
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("fixup script: %v\n%s", err, out)
	}
	return string(out)
}

func writeFiles(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// A base backup of a streaming replica: the script must leave a data dir
// that starts as a primary with no route back to production, and report
// what it removed without echoing the (password-bearing) settings.
func TestBasebackupFixupScriptStandbySource(t *testing.T) {
	dir := t.TempDir()
	writeFiles(t, dir, map[string]string{
		"PG_VERSION":      "17\n",
		"standby.signal":  "",
		"recovery.signal": "",
		"postgresql.auto.conf": "# Do not edit this file manually!\n" +
			"# It will be overwritten by the ALTER SYSTEM command.\n" +
			"primary_conninfo = 'user=replicator password=hunter2 host=prod-primary port=5432'\n" +
			"primary_slot_name = 'replica_1'\n" +
			"work_mem = '8MB'\n",
		"postgresql.conf": "port = 5432\n" +
			"  Restore_Command = 'cp /archive/%f %p'\n" +
			"recovery_target_timeline 'latest'\n" +
			"# primary_conninfo = ''\n" +
			"shared_buffers = 128MB\n",
	})
	out := runFixup(t, dir, "postgres (PostgreSQL) 17.6 (Debian 17.6-1.pgdg13+1)")

	for _, f := range []string{"standby.signal", "recovery.signal"} {
		if _, err := os.Stat(filepath.Join(dir, f)); !os.IsNotExist(err) {
			t.Errorf("%s still present (stat err %v)", f, err)
		}
	}
	auto := readFile(t, filepath.Join(dir, "postgresql.auto.conf"))
	if strings.Contains(auto, "primary_conninfo") || strings.Contains(auto, "primary_slot_name") || strings.Contains(auto, "hunter2") {
		t.Errorf("postgresql.auto.conf still carries replication settings:\n%s", auto)
	}
	if !strings.Contains(auto, "work_mem = '8MB'") || !strings.Contains(auto, "# Do not edit this file manually!") {
		t.Errorf("postgresql.auto.conf lost unrelated lines:\n%s", auto)
	}
	conf := readFile(t, filepath.Join(dir, "postgresql.conf"))
	if strings.Contains(conf, "Restore_Command") || strings.Contains(conf, "recovery_target_timeline") {
		t.Errorf("postgresql.conf still carries recovery settings (names are case-insensitive, = is optional):\n%s", conf)
	}
	for _, keep := range []string{"port = 5432", "# primary_conninfo = ''", "shared_buffers = 128MB"} {
		if !strings.Contains(conf, keep) {
			t.Errorf("postgresql.conf lost %q:\n%s", keep, conf)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "postgresql.conf.pgoverlay")); !os.IsNotExist(err) {
		t.Errorf("temp file left behind (stat err %v)", err)
	}
	if strings.Contains(out, "hunter2") || strings.Contains(out, "prod-primary") {
		t.Errorf("script output leaks the removed settings:\n%s", out)
	}
	c := parseSeededCluster(out)
	if c.dataMajor != "17" || c.serverMajor != "17" {
		t.Errorf("versions data=%q server=%q, want 17/17 (output:\n%s)", c.dataMajor, c.serverMajor, out)
	}
	if strings.Join(c.removed, ",") != "standby.signal,recovery.signal" {
		t.Errorf("removed = %v", c.removed)
	}
	if strings.Join(c.stripped, ",") != "postgresql.auto.conf,postgresql.conf" {
		t.Errorf("stripped = %v", c.stripped)
	}
}

// A primary source (and a Debian-style data dir with no config files at
// all) passes through untouched.
func TestBasebackupFixupScriptPrimarySource(t *testing.T) {
	dir := t.TempDir()
	auto := "# Do not edit this file manually!\nmax_connections = '200'\n"
	writeFiles(t, dir, map[string]string{"PG_VERSION": "15\n", "postgresql.auto.conf": auto})
	out := runFixup(t, dir, "postgres (PostgreSQL) 17.2")
	if got := readFile(t, filepath.Join(dir, "postgresql.auto.conf")); got != auto {
		t.Errorf("postgresql.auto.conf changed:\n%s", got)
	}
	c := parseSeededCluster(out)
	if len(c.removed) != 0 || len(c.stripped) != 0 {
		t.Errorf("reported cleanup on a primary: %+v", c)
	}
	if c.dataMajor != "15" || c.serverMajor != "17" {
		t.Errorf("versions data=%q server=%q, want 15/17", c.dataMajor, c.serverMajor)
	}
}

func fixupResponder(out string) func(int, runtime.HelperSpec) (string, error) {
	return func(i int, s runtime.HelperSpec) (string, error) {
		if len(s.Cmd) > 2 && s.Cmd[2] == basebackupFixupScript {
			return out, nil
		}
		return "", nil
	}
}

func TestSeedRunsFixupOnTheSeededDataDir(t *testing.T) {
	t.Setenv(SSLModeEnv, "")
	d := &recordingDriver{respond: fixupResponder("pgoverlay-data-version=17\npgoverlay-server-version=postgres (PostgreSQL) 17.6\n")}
	s := validSpec()
	s.Network = "net1"
	if err := Seed(context.Background(), d, s); err != nil {
		t.Fatal(err)
	}
	if len(d.helpers) != 3 {
		t.Fatalf("helpers = %d, want 3 (chown prep, pg_basebackup, fixup)", len(d.helpers))
	}
	fx := d.helpers[2]
	if fx.Image != "postgres:17" || fx.User != "postgres" {
		t.Errorf("fixup runs as %q in %q, want postgres in the branch image", fx.User, fx.Image)
	}
	if len(fx.Cmd) != 5 || fx.Cmd[0] != "sh" || fx.Cmd[1] != "-c" || fx.Cmd[4] != "/seed/data" {
		t.Errorf("fixup cmd = %q", fx.Cmd)
	}
	if len(fx.Mounts) != 1 || fx.Mounts[0].Volume != "v" || fx.Mounts[0].Target != "/seed" || fx.Mounts[0].ReadOnly {
		t.Errorf("fixup mounts = %+v, want the seed volume read-write at /seed", fx.Mounts)
	}
	if len(fx.Env) != 0 {
		t.Errorf("fixup env = %v, want none (it never connects to the source)", fx.Env)
	}
}

// A newer pg_basebackup happily copies an older server; branches then die on
// "database files are incompatible with server" behind a 90s readiness wait.
// The mismatch must fail the seed with the fix in the message.
func TestSeedRejectsMajorVersionMismatch(t *testing.T) {
	t.Setenv(SSLModeEnv, "")
	d := &recordingDriver{respond: fixupResponder("pgoverlay-data-version=15\npgoverlay-server-version=postgres (PostgreSQL) 17.6 (Debian 17.6-1.pgdg13+1)\n")}
	err := Seed(context.Background(), d, validSpec())
	if !errors.Is(err, ErrVersionMismatch) {
		t.Fatalf("err = %v, want ErrVersionMismatch", err)
	}
	for _, want := range []string{"PostgreSQL 15", "postgres:17 runs PostgreSQL 17", "--pg-version 15", "db.internal:5432"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q does not mention %q", err, want)
		}
	}
}

// Without the version lines (e.g. logs unavailable on kube) the check is
// skipped rather than failing a seed that may be fine.
func TestSeedSkipsVersionCheckWithoutReport(t *testing.T) {
	t.Setenv(SSLModeEnv, "")
	d := &recordingDriver{respond: fixupResponder("(logs unavailable: timeout)")}
	if err := Seed(context.Background(), d, validSpec()); err != nil {
		t.Fatalf("err = %v, want nil", err)
	}
}

func TestSeedLogsStandbySourceCleanup(t *testing.T) {
	t.Setenv(SSLModeEnv, "")
	var buf bytes.Buffer
	prev := slog.Default()
	slog.SetDefault(slog.New(slog.NewTextHandler(&buf, nil)))
	t.Cleanup(func() { slog.SetDefault(prev) })

	d := &recordingDriver{respond: fixupResponder("pgoverlay-removed=standby.signal\npgoverlay-stripped=postgresql.auto.conf\n" +
		"pgoverlay-data-version=17\npgoverlay-server-version=postgres (PostgreSQL) 17.6\n")}
	if err := Seed(context.Background(), d, validSpec()); err != nil {
		t.Fatal(err)
	}
	logs := buf.String()
	for _, want := range []string{"level=WARN", "standby", "writable primaries", "standby.signal", "postgresql.auto.conf"} {
		if !strings.Contains(logs, want) {
			t.Errorf("log does not mention %q:\n%s", want, logs)
		}
	}
}

func TestSeedFixupFailure(t *testing.T) {
	t.Setenv(SSLModeEnv, "")
	d := &recordingDriver{respond: func(i int, s runtime.HelperSpec) (string, error) {
		if len(s.Cmd) > 2 && s.Cmd[2] == basebackupFixupScript {
			return "", errors.New("helper exited 1: cat: /seed/data/PG_VERSION: No such file or directory")
		}
		return "", nil
	}}
	err := Seed(context.Background(), d, validSpec())
	if err == nil || !strings.Contains(err.Error(), "prepare seeded data dir") || !strings.Contains(err.Error(), "PG_VERSION") {
		t.Fatalf("err = %v, want the fixup failure", err)
	}
}
